= Streamly Kafka Cassandra Samples

This repository contains a spark streaming job that collect data from an unsecured kafka topic and send them to
a table of Cassandra.

== How to build it?

You can run it with Maven

[source,bash]
----
mvn clean install
----

This will produce jar in ../target/streamly-kafka-cassandra-samples-0.0.1-BUILD-SNAPSHOT.jar

== How to test it?

- You go to https://board.streamly.io:10080
- Create an account and login
- Click on the tab MESSAGING
- Create a mqtt topic e.g mynamespace/mqtt/mytopic
- You now have to configure your spark.properties
- Click on the Profile icon
- Copy your access(myacesskey) and secret key(mysecretkey)
- In spark.properties configure the app.args appropriately that is 
-- app.args=192.168.0.141:9093,mynamespace_kafka_topic,mynamespacekafkatocassandra,mynamespacewordcount
-- spark.cassandra.connection.port=9042
-- spark.cassandra.connection.host=192.168.0.141
-- spark.cassandra.auth.username=myacesskey
-- spark.cassandra.auth.password=mysecretkey
- Go to the tab PROCESSING
- Create an application e.g mynamespace-spark-app
- Upload the jar ../target/streamly-kafka-cassandra-samples-0.0.1-BUILD-SNAPSHOT.jar and the file spark.properties
- Start the app
- To publish to kafka, use the kafka client  

[source,bash]
----
bin/kafka-console-producer.sh --broker-list 173.34.175.124:9093 --topic mynamespace_kafka_topic
----

- To verify that this works well, open the cqlsh of cassandra as such 

----
cqlsh 173.34.175.124 19042 -u myacesskey -p mysecretkey
select * from mynamespacekafkatocassandra.mynamespacewordcount;
----

Hope you enjoyed working with streamly.


