= Streamly Mqtt Kafka Samples

This repository contains a spark streaming job that collect data from a secured mqtt topic and send them to
an unsecure and secure kafka topic.

== How to build it?

You can run it with Maven

[source,bash]
----
mvn clean install
----

This will produce jar in ../target/streamly-mqtt-kafka-samples-0.0.1-BUILD-SNAPSHOT.jar

== How to test it?

- You go to https://board.streamly.io:10080
- Create an account and login
- Click on the tab MESSAGING
- Create an unsecured kafka e.g mynamespace-kafka-mytopic and a mqtt topic e.g mynamespace/mqtt/mytopic
- You now have to configure your spark.properties
- Click on the Profile icon
- Copy your access(myacesskey) and secret key(mysecretkey)
- In spark.properties configure the app.args appropriately that is app.args=tcp://192.168.0.141:1883,mynamespace/mqtt/mytopic,mynamespace,myacesskey,mysecretkey,192.168.0.141:9093,mynamespace-kafka-topic,mqttToKafkaApp
- Go to the tab PROCESSING
- Create an application e.g mynamespace-spark-app
- Upload the jar ../target/streamly-mqtt-kafka-samples-0.0.1-BUILD-SNAPSHOT.jar and the file spark.properties
- Start the app
- To publish to mqtt, you might choose to install the mosquitto-clients with  

[source,bash]
----
sudo apt-get install mosquitto-clients -y
mosquitto_pub -h 173.34.175.124 -p 11883 -t mynamespace/mqtt/mytopic -q 1 -m "Hello MQTT!" -u myacesskey -P mysecretkey
----

- To verify that this works well, open a kafka consumer

----
bin/kafka-console-consumer.sh --bootstrap-server 173.34.175.124:19093 --topic mynamespace-kafka-topic --from-beginning
----

Hope you enjoyed working with streamly.


